name: Test

on:
  push:
    paths:
      - "edition-nft/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: cd edition-nft && make test