name: Laliga Test

on:
  push:
    paths:
      - "laliga/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.22'
      - run: go version