name: Test

on:
  push:
    paths:
      - "nft-provider-aggregator/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.20'
      - run: cd nft-provider-aggregator && make test